### ISSUE TITLE
Faulty import in server

### ISSUE THREAD

**Issue by rreinecke** [HydroSysPotsdam/Forester#41]
When executing "run.py" with Python version 3.8.10 on Linux.

```
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    from forester import server
  File "/home/robert/Documents/Projects/FORESTER/Forester/src/forester/server.py", line 6, in <module>
    from .api import API
  File "/home/robert/Documents/Projects/FORESTER/Forester/src/forester/api.py", line 13, in <module>
    from .database import *
  File "/home/robert/Documents/Projects/FORESTER/Forester/src/forester/database/__init__.py", line 12, in <module>
    from .project import Project
  File "/home/robert/Documents/Projects/FORESTER/Forester/src/forester/database/project.py", line 11, in <module>
    from dataclasses_json import dataclass_json
ModuleNotFoundError: No module named 'dataclasses_json'
```

**Comment by david-strahl** [comment]
Included imports for `dataclass_json`, and `rpy2`. Removed unnecessary imports. Fixed a relative import in `validate.py`. 

I cloned the repository, created a clean pip environment and the server seems to work. Maybe you can confirm this @rreinecke before I close this issue?

**Comment by rreinecke** [comment]
Jepp. Server works perfectly.

`pip3 install -r requirements.txt` did install everything necessary for me on Linux.
